services:
  app:
    build: .
    container_name: pitchboxd-server
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    restart: always

    # 2. Grafana Alloy (수집기)
  alloy:
    image: grafana/alloy:latest
    container_name: grafana-alloy
    ports:
      - "12345:12345"
    volumes:
      # [설정 파일 주입] 호스트에 작성한 config.alloy를 컨테이너 안으로 넣어줌
      - ./config.alloy:/etc/alloy/config.alloy
      # [로그 읽기 권한] Spring Boot가 호스트 ./logs에 쓴 파일을 Alloy가 읽을 수 있게 마운트 (ro = 읽기 전용)
      - ./logs:/var/log/myapp:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    depends_on:
      - app

networks:
  default:
    name: pitchboxd-network
