spring:
  mvc:
    async:
      request-timeout: -1
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URL}
            scope: profile, email, openid

jwt:
  secret:
    access_key: ${JWT_ACCESS_SECRET_KEY}
    refresh_key: ${JWT_REFRESH_SECRET_KEY}

expiration:
  access-token-time: ${ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-time: ${REFRESH_TOKEN_EXPIRATION_TIME}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  metrics:
    tags:
      application: pitchboxd-api

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    
decorator:
  datasource:
    p6spy:
      enable-logging: true
      # 콘솔에 여러 줄로 예쁘게(포맷팅) 출력
      multiline: true
      # 쿼리 실행 시간과 파라미터 바인딩 결과 출력
      logging: slf4j