-- Season
INSERT INTO seasons (id, name) VALUES (1, '2026');

-- Teams
INSERT INTO teams (id, name, naver_id) VALUES (1, 'seoul', '09');
INSERT INTO teams (id, name, naver_id) VALUES (2, 'ulsan', '01');
INSERT INTO teams (id, name, naver_id) VALUES (3, 'jeonbuk', '05');
INSERT INTO teams (id, name, naver_id) VALUES (4, 'daejeon', '10');
INSERT INTO teams (id, name, naver_id) VALUES (5, 'bucheon', '26');
INSERT INTO teams (id, name, naver_id) VALUES (6, 'gwangju', '22');
INSERT INTO teams (id, name, naver_id) VALUES (7, 'pohang', '03');
INSERT INTO teams (id, name, naver_id) VALUES (8, 'anyang', '27');
INSERT INTO teams (id, name, naver_id) VALUES (9, 'kimcheon', '35');
INSERT INTO teams (id, name, naver_id) VALUES (10, 'incheon', '18');
INSERT INTO teams (id, name, naver_id) VALUES (11, 'gangwon', '21');
INSERT INTO teams (id, name, naver_id) VALUES (12, 'jeju', '04');

-- Players (240 players)
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (1, 1, 'Seoul_Player_1', 'p_1_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (2, 1, 'Seoul_Player_2', 'p_1_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (3, 1, 'Seoul_Player_3', 'p_1_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (4, 1, 'Seoul_Player_4', 'p_1_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (5, 1, 'Seoul_Player_5', 'p_1_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (6, 1, 'Seoul_Player_6', 'p_1_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (7, 1, 'Seoul_Player_7', 'p_1_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (8, 1, 'Seoul_Player_8', 'p_1_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (9, 1, 'Seoul_Player_9', 'p_1_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (10, 1, 'Seoul_Player_10', 'p_1_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (11, 1, 'Seoul_Player_11', 'p_1_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (12, 1, 'Seoul_Player_12', 'p_1_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (13, 1, 'Seoul_Player_13', 'p_1_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (14, 1, 'Seoul_Player_14', 'p_1_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (15, 1, 'Seoul_Player_15', 'p_1_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (16, 1, 'Seoul_Player_16', 'p_1_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (17, 1, 'Seoul_Player_17', 'p_1_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (18, 1, 'Seoul_Player_18', 'p_1_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (19, 1, 'Seoul_Player_19', 'p_1_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (20, 1, 'Seoul_Player_20', 'p_1_20', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (21, 2, 'Ulsan_Player_1', 'p_2_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (22, 2, 'Ulsan_Player_2', 'p_2_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (23, 2, 'Ulsan_Player_3', 'p_2_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (24, 2, 'Ulsan_Player_4', 'p_2_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (25, 2, 'Ulsan_Player_5', 'p_2_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (26, 2, 'Ulsan_Player_6', 'p_2_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (27, 2, 'Ulsan_Player_7', 'p_2_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (28, 2, 'Ulsan_Player_8', 'p_2_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (29, 2, 'Ulsan_Player_9', 'p_2_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (30, 2, 'Ulsan_Player_10', 'p_2_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (31, 2, 'Ulsan_Player_11', 'p_2_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (32, 2, 'Ulsan_Player_12', 'p_2_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (33, 2, 'Ulsan_Player_13', 'p_2_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (34, 2, 'Ulsan_Player_14', 'p_2_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (35, 2, 'Ulsan_Player_15', 'p_2_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (36, 2, 'Ulsan_Player_16', 'p_2_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (37, 2, 'Ulsan_Player_17', 'p_2_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (38, 2, 'Ulsan_Player_18', 'p_2_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (39, 2, 'Ulsan_Player_19', 'p_2_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (40, 2, 'Ulsan_Player_20', 'p_2_20', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (41, 3, 'Jeonbuk_Player_1', 'p_3_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (42, 3, 'Jeonbuk_Player_2', 'p_3_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (43, 3, 'Jeonbuk_Player_3', 'p_3_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (44, 3, 'Jeonbuk_Player_4', 'p_3_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (45, 3, 'Jeonbuk_Player_5', 'p_3_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (46, 3, 'Jeonbuk_Player_6', 'p_3_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (47, 3, 'Jeonbuk_Player_7', 'p_3_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (48, 3, 'Jeonbuk_Player_8', 'p_3_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (49, 3, 'Jeonbuk_Player_9', 'p_3_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (50, 3, 'Jeonbuk_Player_10', 'p_3_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (51, 3, 'Jeonbuk_Player_11', 'p_3_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (52, 3, 'Jeonbuk_Player_12', 'p_3_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (53, 3, 'Jeonbuk_Player_13', 'p_3_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (54, 3, 'Jeonbuk_Player_14', 'p_3_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (55, 3, 'Jeonbuk_Player_15', 'p_3_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (56, 3, 'Jeonbuk_Player_16', 'p_3_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (57, 3, 'Jeonbuk_Player_17', 'p_3_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (58, 3, 'Jeonbuk_Player_18', 'p_3_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (59, 3, 'Jeonbuk_Player_19', 'p_3_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (60, 3, 'Jeonbuk_Player_20', 'p_3_20', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (61, 4, 'Daejeon_Player_1', 'p_4_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (62, 4, 'Daejeon_Player_2', 'p_4_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (63, 4, 'Daejeon_Player_3', 'p_4_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (64, 4, 'Daejeon_Player_4', 'p_4_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (65, 4, 'Daejeon_Player_5', 'p_4_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (66, 4, 'Daejeon_Player_6', 'p_4_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (67, 4, 'Daejeon_Player_7', 'p_4_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (68, 4, 'Daejeon_Player_8', 'p_4_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (69, 4, 'Daejeon_Player_9', 'p_4_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (70, 4, 'Daejeon_Player_10', 'p_4_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (71, 4, 'Daejeon_Player_11', 'p_4_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (72, 4, 'Daejeon_Player_12', 'p_4_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (73, 4, 'Daejeon_Player_13', 'p_4_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (74, 4, 'Daejeon_Player_14', 'p_4_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (75, 4, 'Daejeon_Player_15', 'p_4_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (76, 4, 'Daejeon_Player_16', 'p_4_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (77, 4, 'Daejeon_Player_17', 'p_4_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (78, 4, 'Daejeon_Player_18', 'p_4_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (79, 4, 'Daejeon_Player_19', 'p_4_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (80, 4, 'Daejeon_Player_20', 'p_4_20', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (81, 5, 'Bucheon_Player_1', 'p_5_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (82, 5, 'Bucheon_Player_2', 'p_5_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (83, 5, 'Bucheon_Player_3', 'p_5_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (84, 5, 'Bucheon_Player_4', 'p_5_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (85, 5, 'Bucheon_Player_5', 'p_5_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (86, 5, 'Bucheon_Player_6', 'p_5_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (87, 5, 'Bucheon_Player_7', 'p_5_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (88, 5, 'Bucheon_Player_8', 'p_5_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (89, 5, 'Bucheon_Player_9', 'p_5_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (90, 5, 'Bucheon_Player_10', 'p_5_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (91, 5, 'Bucheon_Player_11', 'p_5_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (92, 5, 'Bucheon_Player_12', 'p_5_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (93, 5, 'Bucheon_Player_13', 'p_5_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (94, 5, 'Bucheon_Player_14', 'p_5_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (95, 5, 'Bucheon_Player_15', 'p_5_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (96, 5, 'Bucheon_Player_16', 'p_5_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (97, 5, 'Bucheon_Player_17', 'p_5_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (98, 5, 'Bucheon_Player_18', 'p_5_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (99, 5, 'Bucheon_Player_19', 'p_5_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (100, 5, 'Bucheon_Player_20', 'p_5_20', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (101, 6, 'Gwangju_Player_1', 'p_6_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (102, 6, 'Gwangju_Player_2', 'p_6_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (103, 6, 'Gwangju_Player_3', 'p_6_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (104, 6, 'Gwangju_Player_4', 'p_6_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (105, 6, 'Gwangju_Player_5', 'p_6_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (106, 6, 'Gwangju_Player_6', 'p_6_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (107, 6, 'Gwangju_Player_7', 'p_6_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (108, 6, 'Gwangju_Player_8', 'p_6_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (109, 6, 'Gwangju_Player_9', 'p_6_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (110, 6, 'Gwangju_Player_10', 'p_6_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (111, 6, 'Gwangju_Player_11', 'p_6_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (112, 6, 'Gwangju_Player_12', 'p_6_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (113, 6, 'Gwangju_Player_13', 'p_6_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (114, 6, 'Gwangju_Player_14', 'p_6_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (115, 6, 'Gwangju_Player_15', 'p_6_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (116, 6, 'Gwangju_Player_16', 'p_6_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (117, 6, 'Gwangju_Player_17', 'p_6_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (118, 6, 'Gwangju_Player_18', 'p_6_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (119, 6, 'Gwangju_Player_19', 'p_6_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (120, 6, 'Gwangju_Player_20', 'p_6_20', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (121, 7, 'Pohang_Player_1', 'p_7_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (122, 7, 'Pohang_Player_2', 'p_7_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (123, 7, 'Pohang_Player_3', 'p_7_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (124, 7, 'Pohang_Player_4', 'p_7_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (125, 7, 'Pohang_Player_5', 'p_7_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (126, 7, 'Pohang_Player_6', 'p_7_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (127, 7, 'Pohang_Player_7', 'p_7_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (128, 7, 'Pohang_Player_8', 'p_7_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (129, 7, 'Pohang_Player_9', 'p_7_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (130, 7, 'Pohang_Player_10', 'p_7_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (131, 7, 'Pohang_Player_11', 'p_7_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (132, 7, 'Pohang_Player_12', 'p_7_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (133, 7, 'Pohang_Player_13', 'p_7_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (134, 7, 'Pohang_Player_14', 'p_7_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (135, 7, 'Pohang_Player_15', 'p_7_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (136, 7, 'Pohang_Player_16', 'p_7_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (137, 7, 'Pohang_Player_17', 'p_7_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (138, 7, 'Pohang_Player_18', 'p_7_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (139, 7, 'Pohang_Player_19', 'p_7_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (140, 7, 'Pohang_Player_20', 'p_7_20', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (141, 8, 'Anyang_Player_1', 'p_8_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (142, 8, 'Anyang_Player_2', 'p_8_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (143, 8, 'Anyang_Player_3', 'p_8_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (144, 8, 'Anyang_Player_4', 'p_8_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (145, 8, 'Anyang_Player_5', 'p_8_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (146, 8, 'Anyang_Player_6', 'p_8_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (147, 8, 'Anyang_Player_7', 'p_8_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (148, 8, 'Anyang_Player_8', 'p_8_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (149, 8, 'Anyang_Player_9', 'p_8_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (150, 8, 'Anyang_Player_10', 'p_8_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (151, 8, 'Anyang_Player_11', 'p_8_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (152, 8, 'Anyang_Player_12', 'p_8_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (153, 8, 'Anyang_Player_13', 'p_8_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (154, 8, 'Anyang_Player_14', 'p_8_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (155, 8, 'Anyang_Player_15', 'p_8_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (156, 8, 'Anyang_Player_16', 'p_8_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (157, 8, 'Anyang_Player_17', 'p_8_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (158, 8, 'Anyang_Player_18', 'p_8_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (159, 8, 'Anyang_Player_19', 'p_8_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (160, 8, 'Anyang_Player_20', 'p_8_20', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (161, 9, 'Kimcheon_Player_1', 'p_9_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (162, 9, 'Kimcheon_Player_2', 'p_9_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (163, 9, 'Kimcheon_Player_3', 'p_9_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (164, 9, 'Kimcheon_Player_4', 'p_9_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (165, 9, 'Kimcheon_Player_5', 'p_9_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (166, 9, 'Kimcheon_Player_6', 'p_9_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (167, 9, 'Kimcheon_Player_7', 'p_9_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (168, 9, 'Kimcheon_Player_8', 'p_9_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (169, 9, 'Kimcheon_Player_9', 'p_9_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (170, 9, 'Kimcheon_Player_10', 'p_9_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (171, 9, 'Kimcheon_Player_11', 'p_9_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (172, 9, 'Kimcheon_Player_12', 'p_9_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (173, 9, 'Kimcheon_Player_13', 'p_9_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (174, 9, 'Kimcheon_Player_14', 'p_9_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (175, 9, 'Kimcheon_Player_15', 'p_9_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (176, 9, 'Kimcheon_Player_16', 'p_9_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (177, 9, 'Kimcheon_Player_17', 'p_9_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (178, 9, 'Kimcheon_Player_18', 'p_9_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (179, 9, 'Kimcheon_Player_19', 'p_9_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (180, 9, 'Kimcheon_Player_20', 'p_9_20', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (181, 10, 'Incheon_Player_1', 'p_10_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (182, 10, 'Incheon_Player_2', 'p_10_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (183, 10, 'Incheon_Player_3', 'p_10_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (184, 10, 'Incheon_Player_4', 'p_10_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (185, 10, 'Incheon_Player_5', 'p_10_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (186, 10, 'Incheon_Player_6', 'p_10_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (187, 10, 'Incheon_Player_7', 'p_10_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (188, 10, 'Incheon_Player_8', 'p_10_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (189, 10, 'Incheon_Player_9', 'p_10_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (190, 10, 'Incheon_Player_10', 'p_10_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (191, 10, 'Incheon_Player_11', 'p_10_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (192, 10, 'Incheon_Player_12', 'p_10_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (193, 10, 'Incheon_Player_13', 'p_10_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (194, 10, 'Incheon_Player_14', 'p_10_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (195, 10, 'Incheon_Player_15', 'p_10_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (196, 10, 'Incheon_Player_16', 'p_10_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (197, 10, 'Incheon_Player_17', 'p_10_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (198, 10, 'Incheon_Player_18', 'p_10_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (199, 10, 'Incheon_Player_19', 'p_10_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (200, 10, 'Incheon_Player_20', 'p_10_20', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (201, 11, 'Gangwon_Player_1', 'p_11_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (202, 11, 'Gangwon_Player_2', 'p_11_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (203, 11, 'Gangwon_Player_3', 'p_11_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (204, 11, 'Gangwon_Player_4', 'p_11_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (205, 11, 'Gangwon_Player_5', 'p_11_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (206, 11, 'Gangwon_Player_6', 'p_11_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (207, 11, 'Gangwon_Player_7', 'p_11_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (208, 11, 'Gangwon_Player_8', 'p_11_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (209, 11, 'Gangwon_Player_9', 'p_11_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (210, 11, 'Gangwon_Player_10', 'p_11_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (211, 11, 'Gangwon_Player_11', 'p_11_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (212, 11, 'Gangwon_Player_12', 'p_11_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (213, 11, 'Gangwon_Player_13', 'p_11_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (214, 11, 'Gangwon_Player_14', 'p_11_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (215, 11, 'Gangwon_Player_15', 'p_11_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (216, 11, 'Gangwon_Player_16', 'p_11_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (217, 11, 'Gangwon_Player_17', 'p_11_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (218, 11, 'Gangwon_Player_18', 'p_11_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (219, 11, 'Gangwon_Player_19', 'p_11_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (220, 11, 'Gangwon_Player_20', 'p_11_20', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (221, 12, 'Jeju_Player_1', 'p_12_01', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (222, 12, 'Jeju_Player_2', 'p_12_02', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (223, 12, 'Jeju_Player_3', 'p_12_03', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (224, 12, 'Jeju_Player_4', 'p_12_04', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (225, 12, 'Jeju_Player_5', 'p_12_05', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (226, 12, 'Jeju_Player_6', 'p_12_06', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (227, 12, 'Jeju_Player_7', 'p_12_07', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (228, 12, 'Jeju_Player_8', 'p_12_08', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (229, 12, 'Jeju_Player_9', 'p_12_09', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (230, 12, 'Jeju_Player_10', 'p_12_10', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (231, 12, 'Jeju_Player_11', 'p_12_11', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (232, 12, 'Jeju_Player_12', 'p_12_12', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (233, 12, 'Jeju_Player_13', 'p_12_13', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (234, 12, 'Jeju_Player_14', 'p_12_14', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (235, 12, 'Jeju_Player_15', 'p_12_15', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (236, 12, 'Jeju_Player_16', 'p_12_16', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (237, 12, 'Jeju_Player_17', 'p_12_17', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (238, 12, 'Jeju_Player_18', 'p_12_18', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (239, 12, 'Jeju_Player_19', 'p_12_19', NOW());
INSERT INTO players (id, team_id, name, naver_id, created_at) VALUES (240, 12, 'Jeju_Player_20', 'p_12_20', NOW());

-- Matches (12 matches)
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (1, 1, '1R', 1, 2, '2024-03-01 14:00:00', '2024-03-01 16:00:00', 2, 'Stadium', 'm1', NOW(), 2, 1, '[{"playerName": "Seoul_Player_1", "minute": 15}, {"playerName": "Seoul_Player_2", "minute": 40}]', '[{"playerName": "Ulsan_Player_5", "minute": 70}]');
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (2, 1, '2R', 2, 1, '2024-03-08 14:00:00', NULL, 0, 'Stadium', 'm2', NOW(), NULL, NULL, '[]', '[]');
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (3, 1, '1R', 3, 4, '2024-03-01 14:00:00', '2024-03-01 16:00:00', 2, 'Stadium', 'm3', NOW(), 2, 1, '[{"playerName": "Jeonbuk_Player_1", "minute": 15}, {"playerName": "Jeonbuk_Player_2", "minute": 40}]', '[{"playerName": "Daejeon_Player_5", "minute": 70}]');
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (4, 1, '2R', 4, 3, '2024-03-08 14:00:00', NULL, 0, 'Stadium', 'm4', NOW(), NULL, NULL, '[]', '[]');
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (5, 1, '1R', 5, 6, '2024-03-01 14:00:00', '2024-03-01 16:00:00', 2, 'Stadium', 'm5', NOW(), 2, 1, '[{"playerName": "Bucheon_Player_1", "minute": 15}, {"playerName": "Bucheon_Player_2", "minute": 40}]', '[{"playerName": "Gwangju_Player_5", "minute": 70}]');
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (6, 1, '2R', 6, 5, '2024-03-08 14:00:00', NULL, 0, 'Stadium', 'm6', NOW(), NULL, NULL, '[]', '[]');
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (7, 1, '1R', 7, 8, '2024-03-01 14:00:00', '2024-03-01 16:00:00', 2, 'Stadium', 'm7', NOW(), 2, 1, '[{"playerName": "Pohang_Player_1", "minute": 15}, {"playerName": "Pohang_Player_2", "minute": 40}]', '[{"playerName": "Anyang_Player_5", "minute": 70}]');
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (8, 1, '2R', 8, 7, '2024-03-08 14:00:00', NULL, 0, 'Stadium', 'm8', NOW(), NULL, NULL, '[]', '[]');
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (9, 1, '1R', 9, 10, '2024-03-01 14:00:00', '2024-03-01 16:00:00', 2, 'Stadium', 'm9', NOW(), 2, 1, '[{"playerName": "Kimcheon_Player_1", "minute": 15}, {"playerName": "Kimcheon_Player_2", "minute": 40}]', '[{"playerName": "Incheon_Player_5", "minute": 70}]');
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (10, 1, '2R', 10, 9, '2024-03-08 14:00:00', NULL, 0, 'Stadium', 'm10', NOW(), NULL, NULL, '[]', '[]');
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (11, 1, '1R', 11, 12, '2024-03-01 14:00:00', '2024-03-01 16:00:00', 2, 'Stadium', 'm11', NOW(), 2, 1, '[{"playerName": "Gangwon_Player_1", "minute": 15}, {"playerName": "Gangwon_Player_2", "minute": 40}]', '[{"playerName": "Jeju_Player_5", "minute": 70}]');
INSERT INTO matches (id, season_id, round, home_team_id, away_team_id, start_time, finished_at, status, location, naver_id, created_at, home_score, away_score, home_scorers, away_scorers) VALUES (12, 1, '2R', 12, 11, '2024-03-08 14:00:00', NULL, 0, 'Stadium', 'm12', NOW(), NULL, NULL, '[]', '[]');
