-- Season
INSERT INTO seasons (name, created_at) VALUES ('2026', NOW());

-- Teams
INSERT INTO teams (name, naver_id, created_at) VALUES ('seoul', '09', NOW());
INSERT INTO teams (name, naver_id, created_at) VALUES ('ulsan', '01', NOW());
INSERT INTO teams (name, naver_id, created_at) VALUES ('jeonbuk', '05', NOW());
INSERT INTO teams (name, naver_id, created_at) VALUES ('daejeon', '10', NOW());
INSERT INTO teams (name, naver_id, created_at) VALUES ('bucheon', '26', NOW());
INSERT INTO teams (name, naver_id, created_at) VALUES ('gwangju', '22', NOW());
INSERT INTO teams (name, naver_id, created_at) VALUES ('pohang', '03', NOW());
INSERT INTO teams (name, naver_id, created_at) VALUES ('anyang', '27', NOW());
INSERT INTO teams (name, naver_id, created_at) VALUES ('kimcheon', '35', NOW());
INSERT INTO teams (name, naver_id, created_at) VALUES ('incheon', '18', NOW());
INSERT INTO teams (name, naver_id, created_at) VALUES ('gangwon', '21',NOW());
INSERT INTO teams (name, naver_id, created_at) VALUES ('jeju', '04', NOW());

-- Players (240 players)
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_1', 'p_1_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_2', 'p_1_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_3', 'p_1_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_4', 'p_1_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_5', 'p_1_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_6', 'p_1_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_7', 'p_1_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_8', 'p_1_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_9', 'p_1_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_10', 'p_1_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_11', 'p_1_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_12', 'p_1_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_13', 'p_1_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_14', 'p_1_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_15', 'p_1_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_16', 'p_1_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_17', 'p_1_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_18', 'p_1_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_19', 'p_1_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (1, 'Seoul_Player_20', 'p_1_20', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_1', 'p_2_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_2', 'p_2_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_3', 'p_2_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_4', 'p_2_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_5', 'p_2_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_6', 'p_2_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_7', 'p_2_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_8', 'p_2_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_9', 'p_2_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_10', 'p_2_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_11', 'p_2_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_12', 'p_2_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_13', 'p_2_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_14', 'p_2_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_15', 'p_2_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_16', 'p_2_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_17', 'p_2_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_18', 'p_2_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_19', 'p_2_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (2, 'Ulsan_Player_20', 'p_2_20', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_1', 'p_3_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_2', 'p_3_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_3', 'p_3_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_4', 'p_3_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_5', 'p_3_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_6', 'p_3_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_7', 'p_3_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_8', 'p_3_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_9', 'p_3_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_10', 'p_3_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_11', 'p_3_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_12', 'p_3_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_13', 'p_3_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_14', 'p_3_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_15', 'p_3_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_16', 'p_3_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_17', 'p_3_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_18', 'p_3_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_19', 'p_3_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (3, 'Jeonbuk_Player_20', 'p_3_20', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_1', 'p_4_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_2', 'p_4_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_3', 'p_4_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_4', 'p_4_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_5', 'p_4_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_6', 'p_4_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_7', 'p_4_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_8', 'p_4_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_9', 'p_4_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_10', 'p_4_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_11', 'p_4_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_12', 'p_4_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_13', 'p_4_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_14', 'p_4_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_15', 'p_4_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_16', 'p_4_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_17', 'p_4_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_18', 'p_4_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_19', 'p_4_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (4, 'Daejeon_Player_20', 'p_4_20', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_1', 'p_5_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_2', 'p_5_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_3', 'p_5_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_4', 'p_5_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_5', 'p_5_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_6', 'p_5_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_7', 'p_5_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_8', 'p_5_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_9', 'p_5_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_10', 'p_5_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_11', 'p_5_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_12', 'p_5_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_13', 'p_5_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_14', 'p_5_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_15', 'p_5_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_16', 'p_5_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_17', 'p_5_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_18', 'p_5_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES (5, 'Bucheon_Player_19', 'p_5_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 5, 'Bucheon_Player_20', 'p_5_20', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_1', 'p_6_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_2', 'p_6_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_3', 'p_6_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_4', 'p_6_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_5', 'p_6_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_6', 'p_6_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_7', 'p_6_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_8', 'p_6_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_9', 'p_6_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_10', 'p_6_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_11', 'p_6_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_12', 'p_6_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_13', 'p_6_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_14', 'p_6_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_15', 'p_6_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_16', 'p_6_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_17', 'p_6_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_18', 'p_6_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_19', 'p_6_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 6, 'Gwangju_Player_20', 'p_6_20', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_1', 'p_7_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_2', 'p_7_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_3', 'p_7_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_4', 'p_7_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_5', 'p_7_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_6', 'p_7_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_7', 'p_7_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_8', 'p_7_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_9', 'p_7_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_10', 'p_7_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_11', 'p_7_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_12', 'p_7_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_13', 'p_7_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_14', 'p_7_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_15', 'p_7_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_16', 'p_7_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_17', 'p_7_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_18', 'p_7_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_19', 'p_7_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 7, 'Pohang_Player_20', 'p_7_20', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_1', 'p_8_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_2', 'p_8_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_3', 'p_8_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_4', 'p_8_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_5', 'p_8_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_6', 'p_8_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_7', 'p_8_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_8', 'p_8_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_9', 'p_8_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_10', 'p_8_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_11', 'p_8_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_12', 'p_8_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_13', 'p_8_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_14', 'p_8_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_15', 'p_8_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_16', 'p_8_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_17', 'p_8_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_18', 'p_8_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_19', 'p_8_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 8, 'Anyang_Player_20', 'p_8_20', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_1', 'p_9_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_2', 'p_9_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_3', 'p_9_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_4', 'p_9_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_5', 'p_9_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_6', 'p_9_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_7', 'p_9_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_8', 'p_9_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_9', 'p_9_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_10', 'p_9_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_11', 'p_9_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_12', 'p_9_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_13', 'p_9_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_14', 'p_9_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_15', 'p_9_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_16', 'p_9_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_17', 'p_9_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_18', 'p_9_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_19', 'p_9_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 9, 'Kimcheon_Player_20', 'p_9_20', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_1', 'p_10_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_2', 'p_10_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_3', 'p_10_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_4', 'p_10_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_5', 'p_10_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_6', 'p_10_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_7', 'p_10_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_8', 'p_10_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_9', 'p_10_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_10', 'p_10_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_11', 'p_10_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_12', 'p_10_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_13', 'p_10_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_14', 'p_10_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_15', 'p_10_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_16', 'p_10_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_17', 'p_10_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_18', 'p_10_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_19', 'p_10_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 10, 'Incheon_Player_20', 'p_10_20', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_1', 'p_11_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_2', 'p_11_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_3', 'p_11_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_4', 'p_11_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_5', 'p_11_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_6', 'p_11_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_7', 'p_11_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_8', 'p_11_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_9', 'p_11_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_10', 'p_11_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_11', 'p_11_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_12', 'p_11_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_13', 'p_11_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_14', 'p_11_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_15', 'p_11_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_16', 'p_11_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_17', 'p_11_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_18', 'p_11_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_19', 'p_11_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 11, 'Gangwon_Player_20', 'p_11_20', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_1', 'p_12_01', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_2', 'p_12_02', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_3', 'p_12_03', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_4', 'p_12_04', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_5', 'p_12_05', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_6', 'p_12_06', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_7', 'p_12_07', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_8', 'p_12_08', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_9', 'p_12_09', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_10', 'p_12_10', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_11', 'p_12_11', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_12', 'p_12_12', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_13', 'p_12_13', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_14', 'p_12_14', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_15', 'p_12_15', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_16', 'p_12_16', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_17', 'p_12_17', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_18', 'p_12_18', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_19', 'p_12_19', NOW());
INSERT INTO players (team_id, name, naver_id, created_at) VALUES ( 12, 'Jeju_Player_20', 'p_12_20', NOW());
